version: '3.3'

services:
  #service 1: definition of mysql database
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=test
    ports:
      - "3308:3308"
    restart: always


  #service 2: definition of your spring-boot app
  backendservice:
    image: backend
    container_name: backend-app
    build:
      context: .
      dockerfile: backend.dockerfile
    ports:
      - "8084:8084"
    restart: always

    depends_on:
      - db                                
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db/test?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_DATASOURCE_DRIVERCLASSNAME: com.mysql.cj.jdbc.Driver