version: '3.3'

services:
  #service 1: definition of mysql database
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=test
    ports:
      - "3308:3308"
    restart: always


  #service 2: definition of your spring-boot app
  backendservice:                        #it is just a name, which will be used only in this file.
    image: backend               #name of the image after dockerfile executes
    container_name: backend-app  #name of the container created from docker image
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: backend.dockerfile              #docker file name
    ports:
      - "8084:8084"                       #docker containter port with your os port
    restart: always

    depends_on:                           #define dependencies of this app
      - db                                #dependency name (which is defined with this name 'db' in this file earlier)
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db/test?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_DATASOURCE_DRIVERCLASSNAME: com.mysql.cj.jdbc.Driver