/* tslint:disable */
/* eslint-disable */
/**
 * Calendar API
 * API for maintaining Calendar
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CelebrationDto } from './celebration-dto';

/**
 * 
 * @export
 * @interface BaseCalendarDto
 */
export interface BaseCalendarDto {
    /**
     * 
     * @type {string}
     * @memberof BaseCalendarDto
     */
    'date'?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseCalendarDto
     */
    'season'?: string;
    /**
     * 
     * @type {number}
     * @memberof BaseCalendarDto
     */
    'seasonWeek'?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseCalendarDto
     */
    'weekday'?: string;
    /**
     * 
     * @type {Array<CelebrationDto>}
     * @memberof BaseCalendarDto
     */
    'CelebrationList'?: Array<CelebrationDto>;
}

