/* tslint:disable */
/* eslint-disable */
/**
 * Calendar API
 * API for maintaining Calendar
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CalendarDto } from './calendar-dto';

/**
 * 
 * @export
 * @interface BaseCelebrationDto
 */
export interface BaseCelebrationDto {
    /**
     * 
     * @type {string}
     * @memberof BaseCelebrationDto
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseCelebrationDto
     */
    'colour'?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseCelebrationDto
     */
    'ranker'?: string;
    /**
     * 
     * @type {number}
     * @memberof BaseCelebrationDto
     */
    'rankNo'?: number;
    /**
     * 
     * @type {CalendarDto}
     * @memberof BaseCelebrationDto
     */
    'Calendar'?: CalendarDto;
}

