/* tslint:disable */
/* eslint-disable */
/**
 * Calendar API
 * API for maintaining Calendar
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CalendarDtoAllOf
 */
export interface CalendarDtoAllOf {
    /**
     * 
     * @type {number}
     * @memberof CalendarDtoAllOf
     */
    'id': number;
    /**
     * 
     * @type {boolean}
     * @memberof CalendarDtoAllOf
     */
    'deletable': boolean;
}

