/* tslint:disable */
/* eslint-disable */
/**
 * Calendar API
 * API for maintaining Calendar
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BaseCalendarDto } from './base-calendar-dto';
import { CalendarDtoAllOf } from './calendar-dto-all-of';
import { CelebrationDto } from './celebration-dto';

/**
 * @type CalendarDto
 * @export
 */
export type CalendarDto = BaseCalendarDto & CalendarDtoAllOf;


