/* tslint:disable */
/* eslint-disable */
/**
 * Calendar API
 * API for maintaining Calendar
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CalendarDto } from './calendar-dto';

/**
 * 
 * @export
 * @interface TotalCalendarDto
 */
export interface TotalCalendarDto {
    /**
     * 
     * @type {number}
     * @memberof TotalCalendarDto
     */
    'totalRecords'?: number;
    /**
     * 
     * @type {Array<CalendarDto>}
     * @memberof TotalCalendarDto
     */
    'data'?: Array<CalendarDto>;
}

